### ISSUE TITLE
[1.16.2] Parsing error loading recipes

### ISSUE THREAD

**Issue by hattrickpatrick** [Mowmaster/Pedestals#10]
Got 9 errors in my server log about parsing errors loading recipes from this mod.

```
https://pastebin.com/qwRRaYW7


Running forge-1.16.2-33.0.31 and pedestals-1.16.2_0.8

**Comment by Mowmaster** [comment]
Does this cause a game crash, or a dupe bug?

**Comment by Mowmaster** [comment]
forge now has ways to condition recipes based on mods that are or are not loaded, so this should fix this issue... (Untested though)
https://github.com/Mowmaster/Pedestals/commit/0b84d30abd1449179aa94fd7709fc44d8d9d8582
