### ISSUE TITLE
Enhancement: Use of IF's infinity items that are enchanted in block breaker pedestals

### ISSUE THREAD

**Issue by Shindur** [Mowmaster/Pedestals#11]
As the title suggests, allow use of a IF's infinity items to use their enchants on the block breaker. I tested with the infinity drill enchanted with fortune 4 and fortune never applied to the 23 blocks of coal I put through it.

**Comment by Mowmaster** [comment]
Added support in the breaker, 2 choppers, and harvester to support tools based on their class or tool type (Should resolve this issue) Will include in the next weekly update.
https://github.com/Mowmaster/Pedestals/commit/b5526733d604396db04efbb120853702f55e9f99

![image](https://user-images.githubusercontent.com/10681506/92115465-14fb4b80-edb8-11ea-9c3e-d7c3f036574b.png)
