### ISSUE TITLE
No written instructions?

### ISSUE THREAD

**Issue by JustJinxed** [Mowmaster/Pedestals#111]
please consider this an enhancement request, not bug. 

The written instructions don't really hint at how to get a pedestal going, but are pretty general. Could you maybe include a written example of how to get a crushing upgrade installed and working? 

Also didn't see anything about placing the upgrade in the offhand to install. Surely this would be a good "hint". 

(And I realize there's 11 instructional videos- some of us are just not very big fans on watching videos when information can be disseminated in text in much less time)

**Comment by Mowmaster** [comment]
There is a vague description of every item in JEI

Actual docs have been in progress for some time, and are planned to release next 'MAJOR' release.

**Comment by Mowmaster** [comment]
As for examples, those will be part of the actual docs, but the more things we do in docs, the longer it takes to make them.
