### ISSUE TITLE
i can't enchant an advanced book

### ISSUE THREAD

**Issue by MarkusTheThird** [Mowmaster/Pedestals#118]
i tried to enchant the focused book (advanced book) but it won't enchant modpack atm6 to the skies

**Comment by Mowmaster** [comment]
Advanced focus book needs specific requirements.
- An enchanter that can enchant at level 90-120
- An enchanter that can enchant items with treasure type enchants (like soul speed or mending)
- An anvil that can apply any enchant to any item, regardless if it can normally be enchanted or not.

Pedestals xp enchanter may be your only option in most modpacks to enchant this focused book.
Also the xp anvil is also probably the only option to apply this enchant.
