### ISSUE TITLE
[Feature Request] upgrade upgrades

### ISSUE THREAD

**Issue by ShyNieke** [Mowmaster/Pedestals#121]
I want to make a suggestion to allow non RF upgrades to be upgradeable to RF upgrades and maybe even the other way around to.

on a recent playthrough I have been playing with pedestals and while in the coal age I made my pedestal upgrades but now that I am in the RF age I would love to be able to upgrade my non RF upgrades to the ones that use power without needing to make an all new upgrade

**Comment by Mowmaster** [comment]
Closing all 1.16 issues, as I am no longer supporting this version of the game and 1.19+ is a full rewrite, I will however accept and merge any fixes folks make for this version.
