### ISSUE TITLE
Pulling from a fluid exporter causes crash

### ISSUE THREAD

**Issue by GManCometh** [Mowmaster/Pedestals#122]
I tested this in SSP and SMP and it causes crashes in both. It also corrupts the chunk it is in.

If you put a tank down and a pedestal with a fluid export option, and toggle the tank to pull from the exporter pedestal, it will corrupt the chunk and cause a server crash. This only happens if you toggle the pull/push mode while the upgrade is in the pedestal.

I am on Enigmatica 6 V0.5.4

**Comment by GManCometh** [comment]
Did a little more testing. It seems that changing the setting on the tank that allows it to pull from the pedestal is what causes the crash. I want to think that it is specifically when disabling the side that is touching the pedestal.

**Comment by Mowmaster** [comment]
im guessing its similar to : https://github.com/Mowmaster/Pedestals/issues/128
but without a crash report specifically ill never know for sure.

**Comment by GManCometh** [comment]
[crash-2021-10-04_12.48.22-server.txt](https://github.com/Mowmaster/Pedestals/files/7279844/crash-2021-10-04_12.48.22-server.txt)

**Comment by GManCometh** [comment]
It is specifically when you disable the side

**Comment by Mowmaster** [comment]
alright cool, seems to be the exact same issue as #128

**Comment by GManCometh** [comment]
This one works even with fluid in the tank

**Comment by Mowmaster** [comment]
yeah, but in the code when switching the sidedness up, im guessing its creating a similar issue.

**Comment by Mowmaster** [comment]
Closing all 1.16 issues, as I am no longer supporting this version of the game and 1.19+ is a full rewrite, I will however accept and merge any fixes folks make for this version.
