### ISSUE TITLE
Crash loop with Auto Attacker

### ISSUE THREAD

**Issue by MuteTiefling** [Mowmaster/Pedestals#13]
Version: Pedestals -1.16.1_0.8

[latest.log](https://github.com/Mowmaster/Pedestals/files/5204183/latest.log)
[crash-2020-09-10_15.15.33-server.txt](https://github.com/Mowmaster/Pedestals/files/5204184/crash-2020-09-10_15.15.33-server.txt)

The crash occured while attempting to kill Vindicators with an.. ahem, heavily enchanted weapon installed in the pedestal. I'm restoring from backup right now to see if I can provide more info or replicate with an unenchanted weapon to help narrow things down. Will report back shortly.

**Comment by MuteTiefling** [comment]
Ah, no it has nothing to do with the weapon. The Auto Attacker is just crashing when attacking Vindicators. No weapon involved. 

[latest.log](https://github.com/Mowmaster/Pedestals/files/5204274/latest.log)
[crash-2020-09-10_15.36.13-server.txt](https://github.com/Mowmaster/Pedestals/files/5204275/crash-2020-09-10_15.36.13-server.txt)

**Comment by Mowmaster** [comment]
https://github.com/Mowmaster/Pedestals/commit/4ed63db9a60f426bfd6c28483f89bee7c737a53b
fixed, just haven't released the update yet since im changing some core pedestal stuff too.
