### ISSUE TITLE
Upgraded Pesestals will not generate Marble from AStral Sorcery.

### ISSUE THREAD

**Issue by Furious1964** [Mowmaster/Pedestals#132]
I placed either 1 block or Raw Marble or 1 block of Marble Bricks under it and it still won't generate Marble when the Pedestal is upgraded with the Cobble Gen Upgrade. Please look into this.

**Comment by DeadTrapsDevelopment** [comment]
Marble is not in the recipe list of the CobbleGen upgrade.
https://github.com/Mowmaster/Pedestals/tree/b16cf86b647617a68d4caf86b3024cf329d15df8/src/main/resources/data/pedestals/recipes/pedestal_cobblegen
Here u see all possible recipes

**Comment by DeadTrapsDevelopment** [comment]
If u want to add new outputs for them
install Crafttweaker and create a anyname.zs in your scripts folder.
and insert this as example:


<recipetype:pedestals:cobblegen>.addJSONRecipe("thisneedstobeauniquename", {
  "type": "pedestals:pedestal_cobblegen",
  "ingredient": {
    "item": "minecraft:clay"
  },
  "result": {
    "item": "minecraft:clay",
    "count": 1
  }
});

If u play 1.16.5 u can use /reload to reload the complete server/client.
in 1.12.2 u need to restart the game

**Comment by DeadTrapsDevelopment** [comment]
To get the id/name of the marble of your mod use /crafttweaker hand "while holding it in your hand in minecraft"
use only modname:itemname ignore the <item: part and the <>.

**Comment by DeadTrapsDevelopment** [comment]
This is for 1.16.5 if u need for 1.12.2 or other versions pls pm me in discord Tarantel#7422

**Comment by Mowmaster** [comment]
(Pedestals isn't in 1.12, and the mod I have for 1.12 doesn't have this feature)

Kube JS is another option, if you crack open the scripts in either atm6 or e6 packs they both modify some of the cobble gen recipes, so you can just add to their scripts of you want this option. You generally need the registration name of the block/item which f3+h in game can enable the advanced tooltips and the registration name is usually listed at the very bottom of the tooltip in this format
modid:blockName

**Comment by Mowmaster** [comment]
If you HAVE the recipe listed in jei and have the correct setup and its not working.
Post images showing both and we can further assist you if its not related to simply not being a recipe in your pack.

**Comment by Furious1964** [comment]
OK, thanks for letting me know.

**Comment by DeadTrapsDevelopment** [comment]
> (Pedestals isn't in 1.12, and the mod I have for 1.12 doesn't have this feature)

Yeah dont know thats no 1.12 version for Pedestals ^^
Posted only to help him^^
