### ISSUE TITLE
Feature suggestion

### ISSUE THREAD

**Issue by EnabledEnzo** [Mowmaster/Pedestals#133]
When you are running a breaker and dont need the xp it can be tedious dealing with it especially if you have multiple running i suggest a void augment where it voids the xp instead of spitting it out.

**Comment by Mowmaster** [comment]
Mhmm, yeah i can add an xp void, like i have for items/entities, fluids, and energy.
But using an xp magnet near your breakers to absorb the orbs then store them in a xp tank will probably take care of it. if you fill up a capacity 5 tank, then get the 'Advanced' enchant and throw capacity 5+ on it, capacity XX gets you 20k levels of storage

**Comment by Mowmaster** [comment]
Closing all 1.16 issues, as I am no longer supporting this version of the game and 1.19+ is a full rewrite, I will however accept and merge any fixes folks make for this version.
