### ISSUE TITLE
Pedestals Itemstorage voids items if connected via RS external Storage

### ISSUE THREAD

**Issue by Darkere** [Mowmaster/Pedestals#136]
When connecting a pedestal with the Item Tank upgrade to an RS external storage, some items will be voided if you attempt to autocraft with them.

Unsure what happens, as the numbers don't make sense. Requested a craft requiring 300 stone, and was missing 860 stone afterwards.

pedestals-0.8s_hotfix_5

Original issue here: https://github.com/NillerMedDild/Enigmatica6/issues/3114

**Comment by Mowmaster** [comment]
Closing all 1.16 issues, as I am no longer supporting this version of the game and 1.19+ is a full rewrite, I will however accept and merge any fixes folks make for this version.
