### ISSUE TITLE
[Feature Request] Render Augment

### ISSUE THREAD

**Issue by Mowmaster** [Mowmaster/Pedestals#138]
Will prevent the upgrade or items from rendering on the pedestal.

Crouch + Right click the augment to change modes:
Loops between:
- Both won't render (default)
- upgrade won't render
- item won't render

Crafted with paper around a pane of any glass = 8
[P][P][P]
[P][G][P]
[P][P][P]

Augment in offhand + right click to insert.
Augment in offhand + left click to remove.

**Comment by Mowmaster** [comment]
Should help with this: https://github.com/Mowmaster/Pedestals/issues/131

Not a fix, but should be a nice improvement for now.

**Comment by Mowmaster** [comment]
https://github.com/Mowmaster/Pedestals/commit/ef73b8e30929d53991b6ef8d3ca61a98563288b2

**Comment by SGZ-Creations** [comment]
Think #147 is simular to this tho deffently not sure.
