### ISSUE TITLE
Color Pallet not applying to pedestal, instead being displayed

### ISSUE THREAD

**Issue by Catomax262** [Mowmaster/Pedestals#142]
The same applies to the glowstone. Why?

**Comment by Mowmaster** [comment]
Both have to be in the offhand and right click to apply it, the color palette has to be applied before anything else is done to the pedestal, or it wont work.
and the glowstone should be able to be applied whenever.

**Comment by Mowmaster** [comment]
check out the #pedestals-116 channel on the discord https://discord.gg/TGZSt7k if you have any other interaction questions, as most of it pinned or has been talked about and can be searched for in the channel
