### ISSUE TITLE
Reset linking tool

### ISSUE THREAD

**Issue by djmattyg007** [Mowmaster/Pedestals#143]
If I discover that the pedestal I'm trying to link is too far away, and then I destroy the pedestal I'm linking, the linking tool gets stuck. There should be a way to cancel the linking process.

**Comment by Mowmaster** [comment]
There is, Crouch Right Click any Non Pedestal Block to Clear the Tool.

**Comment by djmattyg007** [comment]
Would you be able to add that to the wiki?
https://github.com/Mowmaster/Pedestals/wiki/Linking-Tool

**Comment by Mowmaster** [comment]
I could probably do one better, and just use this: https://github.com/Mowmaster/Dust/wiki/Linking-Tools

The tool hasnt changed much for 1.18 so itll be about the same and i can just reuse some work this way
