### ISSUE TITLE
[Feature Request] Linking tool overwrites Morphing Tool (Morph-o-Tool)

### ISSUE THREAD

**Issue by kirjorjos** [Mowmaster/Pedestals#144]
I started by putting the linking tool on my Morphing tool, and upon shift clicking the air by mistake, it turned into a backwards linking tool voiding my morphing tool.  A potential fix could be to preserve NBT upon swapping between the forward and backward linking tool.  Sorry if I'm missing anything, I'm not very good at bug reports or issues.

**Comment by Mowmaster** [comment]
Pretty sure the Morph Tool has a keybind to swap tools in it, use that, or the pack needs to disable the linking tool from being inside this object, as the Linking tool is also used in crafting, and there is no way with JSON crafting recipes to transfer nbt over to the resulting product that im aware of.

Also the Upgrade Tool/Tool Swapper/Filter Tool/Tag Tool all have a similar functionality, so be mindful of those as well. In essence pedestals only has 2 Tools you need to have on you, if your not using the mod then you can just store those items. 

I am currently working with version 1.18+ only now, so there is a very good chance this will never be 'fixed' in the way you want.

**Comment by Mowmaster** [comment]
Closing all 1.16 issues, as I am no longer supporting this version of the game and 1.19+ is a full rewrite, I will however accept and merge any fixes folks make for this version.
