### ISSUE TITLE
Server are loging full pipe & laggs server

### ISSUE THREAD

**Issue by SGZ-Creations** [Mowmaster/Pedestals#147]
MC version 1.16.5  mod pack is ATM6 V 1.8.7
mod V of pedestal : 0.8s_hotfix_5
mod V of mekanism : 10.0.21.448

Hey have been looking in configs after a way to decrese the pedestal push & storage as it lags the server quit a lot. + as mekanism are loging an overload from the the pedestal. Possebly becaus u made it work as the hopper. So if u could figure out a way to make it work without the hopper function/mechanic that would do a lot on the lag portion. Since hoppers is know to casue lag on servers even vanilla have i heard & been told that.

image of the loging
![image](https://user-images.githubusercontent.com/59801736/150202139-658c4b3f-9438-4d26-aa7d-791769bf177e.png)

So if u could look at this and possible optimize the cobble gen funtion to make it less i would apriciate it. 

Also would like to see a config about decressing the amount of cobble or any block gen to have a changeble limit in/to them. Instead of the forced 2.x G that it has now.

Should the issue lay with mekanism would u be kind to farward a post to them and possebly work the case toghetter ?

**Comment by Mowmaster** [comment]
Closing all 1.16 issues, as I am no longer supporting this version of the game and 1.19+ is a full rewrite, I will however accept and merge any fixes folks make for this version.

**Comment by SGZ-Creations** [comment]
So this wil never be fixed ?

**Comment by Mowmaster** [comment]
On the Forge side of mods, I am a 1 person team, and currently 100% of my available dev time is going into 1.19+
unless some kind soul pr's a fix, or somehow I magically manage to complete all my 1.19 mods (I've never managed to complete a single mod before a new MC version release yet) the 1.16 version will not see any further development from me.

**Comment by Mowmaster** [comment]
if this issue manages to make it through a full rewrite, then i will address it in 1.19 and potentially backport it, providing it doesnt require too much additional effort.

**Comment by SGZ-Creations** [comment]
Ok kinda sad to hear u leave for 1.19 and not finishing. Just curious to why not remove any un done project and fix bugs that shows up. Just that gives sort of complete mod as is. And whenever there are no much bugs left work on newer version's. Just a genaral ide i would do tho i work on Factorio.

**Comment by Mowmaster** [comment]
1. Removing a project would break every pack / world that its in.
2. I am unmotivated to continue working on the older version(s), I've also attempted to work on it during 1.18, which resulted in prolonged creative burnout.
3. This is not my job, I have very little incentive to complete something I will never receive full compensation for. Plus every new version is a chance to rewrite, refactor, and improve the mod, without worring I may break someones 2 year old world.

**Comment by SGZ-Creations** [comment]
Well theres a reson for mod pack versions + a change log since say a item got removed would simply tell me that "oh don't update it can break shit". Or copy the save move it to a seprete place to test and see if it breaks also a reson all should do backups.

**Comment by Mowmaster** [comment]
I will not budge on this decision unless you happen to have enough spare cash to hire me full time as a java developer, or can afford to commission me to do the work. (The current work comes out to around $15000 thus far)

Thus, if it pains you, feel free to remove my mods from any packs you play, no one is forcing you to deal with the issues, despite how useful the mod is otherwise.

**Comment by SGZ-Creations** [comment]
Well i can't easily remove the mod if i wanted to as for the pack creators adding progress system. And i are not starting to code in a diffrent language yet. And if i would ever hire some it would be at my local currency. And that is not $
