### ISSUE TITLE
You can't break a pedestal in creative mode

### ISSUE THREAD

**Issue by User-12691296** [Mowmaster/Pedestals#148]
Simple bug. Really annoying. Whenever you left click on a pedestal, it removes an item, and when all the items and upgrades are gone, nothing else happens, it just displays the breaking particles.

My info comes from playing E6E creative, (which I do believe is the main modpack supporting this awesome mod rn, so even if it's not a universal thing, it still might be worth fixing) and in vanilla, there is no way to break this without going to survival, or using tnt.

**Comment by Mowmaster** [comment]
gotta have the dev tool in your inventory first.

**Comment by aaronhowser1** [comment]
Doesn't work in `pedestals-0.2.30`, either hitting the pedestal with the dev tool or with hand while dev tool is in inventory

**Comment by Mowmaster** [comment]
https://github.com/Mowmaster/Pedestals/wiki/Dev-Tool119
