### ISSUE TITLE
Pedestal auto-killer doesn't work with Tinkers Construct Mobs

### ISSUE THREAD

**Issue by Rothlan284** [Mowmaster/Pedestals#156]
I'm attempting to auto-kill skyslime with an "Infinity Hammer" from the "Industrial Forgoing" mod, but the "auto-killer" upgrade does not target any mobs from "Tinkers Construct". I'm not sure if this is really an "issue" compared to an "incompatibility" , so I do hope that it isn't a waste of time or effort for Mowmaster to read/implement.

**Comment by Mowmaster** [comment]
which version is this for?

**Comment by Rothlan284** [comment]
1.16.5

It seems to work fine with all mobs not from TiC.

**Comment by Mowmaster** [comment]
this issue is for an old version and i have no intention on fixing this without a pr
