### ISSUE TITLE
Suggestion: More Upgrade Modifications

### ISSUE THREAD

**Issue by Mowmaster** [Mowmaster/Pedestals#159]
Round Robbin would be nice so an export can pull from its multiple pedestal slots into an inv
or Import can pull round robin from chest slots

**Comment by mfrankov** [comment]
With the overhaul to Import/Export, it's less clear the suggested modification would make sense (especially given the remote inventory, as if anything round-robin there might be useful). I'm happy to re-investigate implementing something if we find something we'd like given the new upgrade behavior, but for now I think this specific issue can be resolved.
