### ISSUE TITLE
Energy Importer Upgrade causes crash.

### ISSUE THREAD

**Issue by giveashift** [Mowmaster/Pedestals#16]
If you place the Stone or Granite (from vanilla Minecraft) or Redia Tool (from Engineer's Decor) into a Pedestal with an Energy Importer Upgrade it immediately crashes the game. The world loads up following the initial crash but immediately crashes again. I'm going to assume its any item placed but that's all I tested before getting tired of reloading the game to test.

I created a new world and did some testing, placing (seemingly) any item into the Pedestal without the Energy Importer Upgrade does not result in a crash. The Energy Exporter and Energy Relay Upgrades do not result in a crash either, as well as the handful of other random upgrades I tested did not result in a crash either.

Minecraft Version: 1.16.2
Forge Version: 33.0.37 (All the Mods 6 v1.0.7) and 33.0.61 (fresh instance containing only Pedestals)
Pedestal Version: 1.16.2_0.8

All the Mods 6 crash report: https://gist.github.com/giveashift/ffe312dcefd773555426720e4810267c
Pedestal Only crash report: https://gist.github.com/giveashift/d10f7e057091adec5f991505dfbe1ff8

**Comment by giveashift** [comment]
Just realized the ticking block entity issue reported below, I'll leave this for now in case you want to look at more crash reports but this is duplicate and feel free to remove.

**Comment by Mowmaster** [comment]
#12
