### ISSUE TITLE
[Suggestion] Some sort of better work area alert when none is present

### ISSUE THREAD

**Issue by Mowmaster** [Mowmaster/Pedestals#164]
Currently the work area will pop up and stay active until the issue is resolved.

while this *DOES* get folks attention, its been perceived as a bug

some alert system using an '!' might be more ideal

**Comment by Mowmaster** [comment]
some work in this area, added a visualizer to show work area range (the area the work selection must be within) [color is blue, for the render, red is linking range]
![image](https://user-images.githubusercontent.com/10681506/225332225-cb8bb577-23d3-4724-b9ea-c4b2d3e41c42.png)

**Comment by Mowmaster** [comment]
considering these options for new ways to notify folks if a work area is needed

1. work area (blue box) pops up if no work area is selected, will not go away till one is selected.
2. work area (blue box) pops up if no work area is selected, will not go away till one is selected.  AND  some text rendered above the pedestal saying something to the effect of "work area needs selected".
3.  some text rendered above the pedestal saying something to the effect of "work area needs selected".

**Comment by Saereth** [comment]
I would say 3 if only for the issue of when I had multiple pedestals out that needed areas defined it got very confusing visually

**Comment by Mowmaster** [comment]
okay sounds good.

**Comment by Mowmaster** [comment]
![image](https://user-images.githubusercontent.com/10681506/226527656-59d9dcea-5275-464d-8ad1-cd1b2bd71ae5.png)

**Comment by Saereth** [comment]
neat! that looks good

**Comment by Mowmaster** [comment]
https://www.curseforge.com/minecraft/mc-mods/pedestals/files/4450996

https://youtu.be/8Nzkuvq8hZw
