### ISSUE TITLE
[BUG]: Looking at a block gen pedestal causing crashes 1.19

### ISSUE THREAD

**Issue by KP-Names** [Mowmaster/Pedestals#173]
I have a pedestal generating sand, and when I started using it, it was fine, but after I left it to run for a while, I found any time my pointer passed over it, it would crash my game. I know it was the pedestal because after I carefully encased it in stone so I couldn't view it as a player, it wasn't crashing anymore. I was pulling from it using the Pipez mod, but the inventory it was pulling into was full so it was backing up into the pedestal. 

[2023-03-17-2.log](https://github.com/Mowmaster/Pedestals/files/11132743/2023-03-17-2.log)
[crash-2023-03-17_19.00.55-server.txt](https://github.com/Mowmaster/Pedestals/files/11132744/crash-2023-03-17_19.00.55-server.txt)

**Comment by Mowmaster** [comment]
should be fixed in v0.2.39+
