### ISSUE TITLE
magnet upgrade deletes items

### ISSUE THREAD

**Issue by SveetPickle** [Mowmaster/Pedestals#18]
The magnet upgrade seems to be deleting items if it trys to pick something up while moving items to another pedestal.

Edit: I'm playing on the latest 1.16.3 version.

**Comment by Mowmaster** [comment]
I think i know whats going on, sounds like i just forgot a check when the pedestal is full. ill try to push a fix soonish

**Comment by Mowmaster** [comment]
https://github.com/Mowmaster/Pedestals/commit/9db216f38f0f03ae05e54ff22e77648cd1c91e9b
Fixed and this will be out in an update tonight (oct 24th,2020)
