### ISSUE TITLE
bug: recycler upgrade not ejecting bows

### ISSUE THREAD

**Issue by Mowmaster** [Mowmaster/Pedestals#186]
recyler doesnt output bow items

**Comment by mfrankov** [comment]
Fix for 1.19: https://github.com/Mowmaster/Pedestals/commit/0cab3d9af33a45e90c3d9d6e001979bd32cca666
Fix for 1.20:
https://github.com/Mowmaster/Pedestals/commit/efd24a55f51b6e4ce8ae13d1ba9d084ea66aa6da
