### ISSUE TITLE
bug: placer upgrade not correctly placing blocks if it has multiple slots

### ISSUE THREAD

**Issue by Mowmaster** [Mowmaster/Pedestals#189]
placer in a pedestal with multiple slots
will place the first item ONLY for each items in the other slots (it does properly remove items, but the last one first, instead of the first one in the 'list')
![image](https://user-images.githubusercontent.com/10681506/232182138-54c67b4e-215e-4704-bbed-2803731f1bc8.png)

**Comment by mfrankov** [comment]
Seems related to https://github.com/Mowmaster/Pedestals/issues/219, although I think this would need to store some data around which block it's trying to place next since I don't see why it would cycle through inventory slots otherwise.

**Comment by mfrankov** [comment]
Should be "fixed in dev" given the PR with `BlockPlacer` was already merged (assuming I understood what this bug was trying to flag). The new behavior should indeed only place items from the first slot, but will also remove those items rather than the last one first.

**Comment by Mowmaster** [comment]
also fixed with this pr: https://github.com/Mowmaster/Pedestals/pull/224

**Comment by Mowmaster** [comment]
1.19 released in this version: https://github.com/Mowmaster/Pedestals/commit/1c83f5684a4a84458dbea05b8840644e52af1bbc
