### ISSUE TITLE
[1.16.3] Fake player not working again (Double checked fake players)

### ISSUE THREAD

**Issue by YOYOK9** [Mowmaster/Pedestals#19]
I recently updated FTB Chunks, and essentials (not sure the second one matters but its info) and my pedestals no longer are able to place blocks. I saw the other issue about adding [Minecraft] fake user to my claim and double checked that first. It is allowed. 
https://puu.sh/GFUrS/54e5323c2b.png 

There is a secondary minecraft user but I cant add it for what ever reason. The one in the picture is the Fake user and has the uuid to match https://puu.sh/GFUtW/60e3446040.png , However I can hear the sound of blocks being placed and if I remove the claim on the chunk it works just as its supposed too. 

Not sure if this would be an issue for you or ftbteams/chunks. 

MC: 1.16.3
Forge: 34.1.23
FTB:Chunks: 1603.1.2.39
Ranks: 1.0.0.7
Essentials: 1603.1.0.8
Teams: 1.0.1.12

**Comment by Mowmaster** [comment]
Well i did some testing and this isnt an issue in SinglePlayer, Im trying to load the BusinessElitePlus pack up on my server to test that next. But eventually this wont be an issue, im planning to try and make it so the fake player will be bound to the player's uuid eventually, which will hopefully get rid of needing to set it as an allie

**Comment by Mowmaster** [comment]
Okay going to close this. https://github.com/Mowmaster/Pedestals/commit/cd45c744d2375921dc0561c66c4a09975990a03d should fix any issues with players and pedestals in claimed chunks. Upgrades now store who placed them in a pedestal, and will use that users uuid when trying to break/place blocks in the world.
