### ISSUE TITLE
Suggestion: Smelter/smoker/blaster Capacity increase smelted amount?

### ISSUE THREAD

**Issue by Mowmaster** [Mowmaster/Pedestals#194]

**Comment by mfrankov** [comment]
As mentioned in discord, I'll pick this up as part of a refactor onto the new recipe caching code.

**Comment by mfrankov** [comment]
Didn't handle this in the PR I just cut as it's actually a little odd to reconcile how to do this alongside speed (given speed is just a multiplier on progress and doesn't change the actual ticking interval, so capacity would also just be a multiplier on progress but raises questions around whether you always have to process the full augmented capacity worth [if you can output less than full capacity worth at a time it's literally just a second speed augment]).

**Comment by mfrankov** [comment]
Closing this out as per my last comment -- it's not clear how we'd handle capacity given how speed is handled in these upgrades (which is just a multiplier on progress, not a change to the number of ticks required per operation). If you can think of another way to have capacity be meaningfully different either of us can try to implement based on a new issue, but it seems worth cleaning up the issues queue.
