### ISSUE TITLE
BUG: Smelter speed tooltip doesnt reflect its actual max amount

### ISSUE THREAD

**Issue by Mowmaster** [Mowmaster/Pedestals#195]

**Comment by mfrankov** [comment]
Commit for 1.19: https://github.com/Mowmaster/Pedestals/commit/110e5f0ac756927ebdaead2603b880076092dc58
Commit for 1.20: https://github.com/Mowmaster/Pedestals/commit/2708c14c699a9a7406fea9b4ad5f0169285a8b14

**Comment by Mowmaster** [comment]
1.19 released in this version: https://github.com/Mowmaster/Pedestals/commit/1c83f5684a4a84458dbea05b8840644e52af1bbc

**Comment by Mowmaster** [comment]
1.20 fixed: https://github.com/Mowmaster/Pedestals/commit/55918833e4bb5dcbdaa35c038045c66df83659b5
