### ISSUE TITLE
[Bug] Fertilizer Upgrade can be tricked into using anything as bonemeal.

### ISSUE THREAD

**Issue by mfrankov** [Mowmaster/Pedestals#219]
I discovered this while doing a refactor for https://github.com/Mowmaster/Pedestals/pull/218 (which does not try to solve this bug as it's already a pretty huge change).

To replicate this bug, setup a pedestal with storage upgrades so it holds at least 2 stacks of items. Place in a stack of bonemeal first, then a stack of anything (I used stone). Create a valid work area and insert it, then add a Fertilizer upgrade. Once you observe that the fertilizer upgrade did indeed bonemeal, use an upgrade tool to remove the Fertilizer upgrade (just to make verifying easier). If you check the contents of the pedestal you'll notice you have the same amount of bonemeal as originally added to the pedestal, but have less of the second stack of items (as they were removed instead of bonemeal as part of performing the action).

Basically caused as the upgrade checks if bonemeal is present using `pedestal.getItemInPedestal()` [on line 420 of the upgrade code](https://github.com/Mowmaster/Pedestals/blob/1.19-Forge/src/main/java/com/mowmaster/pedestals/Items/Upgrades/Pedestal/ItemUpgradeFertilizer.java#L420) which returns the item in the _first_ inventory slot, and then uses `pedestal.removeItem(1,false)` [on line 431](https://github.com/Mowmaster/Pedestals/blob/1.19-Forge/src/main/java/com/mowmaster/pedestals/Items/Upgrades/Pedestal/ItemUpgradeFertilizer.java#L431) which removes an item from the _last_ inventory slot. Presumably should be fixed by changing this to call `removeItemStack(ItemStack stackToRemove, boolean simulate)` and passing in a copy of `stackInPed` containing 1 item (although that makes me wonder if these should also be modified to use something other than `getItemInPedestal` that checks if _any_ of the slots contain the required item). The `removeItem` calls likely need to stay as-is to not break inserting/removing items from players as I'm pretty sure you do want this to work like a stack and not a queue.

Also seems likely this impacts all upgrades that use `removeItem(int numToRemove, boolean simulate)`, which based on usages shown via IntelliJ are the `BlockPlacer`, `Breeder`, `Crafter`, `Dropper`, `Filler`, `Generator_FurnaceFuels`, `HiveHarvester`, `Milker`, `Modifications`, `Planter`, and `Pump`. I didn't check how all of these work, but I did at least verify that this same bug occurs with the `Generator_FurnaceFuels` which is happy to burn stone from the second and third inserted stack instead of the single charcoal I provided it. I also doubled checked and this is not present for the `Dropper` as that takes the result of the `pedestal.removeItem(countToDrop,false)` call (assigned to `dropMe`) and drops that instead, which means there's a bit of confusion in the code as `itemToDrop` obviously isn't the item to drop (and in the case of multiple stacks existing in the pedestal will certainly not match `dropMe`).

**Comment by mfrankov** [comment]
Reading the code of the potentially impacted upgrades...

**Not Impacted:**
* `Dropper` works correctly, but the code is a bit confusing (it has a variable `itemToDrop` and a second variable `dropMe` and it does indeed drop `dropMe` which it should do, but some of the computations there are done based on `itemToDrop` which in a pedestal with multiple storage slots wouldn't necessarily compute the correct thing).


**Impacted:**
* `BlockPlacer` will place what's in the first slot, but remove items from the last slot (block duplication)
* `Breeder` will feed what's in the first slot, but remove items from the last slot (food duplication)
* `Crafter` I'm pretty sure will craft based on recipes determined from the first slots, but remove from the last slots (item duplication)
* `Filler` will place what's in the first slot, but remove items from the last slot (block duplication). I'm also a little confused at the need for both `BlockPlacer` and `Filler` as they seem basically identical in purpose (except `Filler` is meant to be "rapid"?).
* `Generator_FuranceFuels` will burn whatever's in the first slot, but remove items from the last slot (fuel duplication)
* `HiveHarvester` I'm unclear what the intent of the `removeItem` is, because it seems to only be reached if you have a toolStack in the pedestal but it's not damageable (at which point regardless of whether damage is enabled it removes the tool?). The upgrade also seems to double-damage the tool if damage is enabled (on L473 and L481).
* `Milker` will fill whatever was in the first slot, but remove items from the last slot (I assume buckets? I've actually never used this upgrade)
* `Modifications` will determine the recipe based on what's in the first slot, but remove items from the last slot (item duplication)
* `Planter` will plant what's in the first slot, but remove items from the last slot.
* `Pump` will replace the fluid with what's in the first slot, but remove items from the last slot (block duplication).

For all of those "duplication" is really I suppose a swap of the item that's in the last slot in place of the item that's in the first slot, but given cobble gens are relatively easy even with just Pedestals it means you can use cobble in place of any item or block required by these impacted upgrades.

**Comment by mfrankov** [comment]
Previously fixed `BlockPlacer`, `Pump`, `Generator_FurnaceFuels`.

Begun additional fixes with `Planter`, `Breeder`, and `Crafter` (in https://github.com/Mowmaster/Pedestals/pull/224/commits/706ed555fa12b3e93b321438750de0a3d9bed92c).

**Comment by mfrankov** [comment]
`HiveHarvester`, `Milker` and `Filler` have all been fixed. This just leaves `Modifications`.

**Comment by mfrankov** [comment]
And `Modifications` is now also completed in https://github.com/Mowmaster/Pedestals/commit/384adc84be60e94e80759431b1559b9b18caddbb so all upgrades with this issue have been fixed.

**Comment by Mowmaster** [comment]
released in this version: https://github.com/Mowmaster/Pedestals/commit/1c83f5684a4a84458dbea05b8840644e52af1bbc
