### ISSUE TITLE
Bee Hive Harvester

### ISSUE THREAD

**Issue by Rithenar** [Mowmaster/Pedestals#22]
The Bee Hive Harvester Upgrade, when used with mods like Resourceful Bees, is turning all honeycombs into vanilla honeycombs. In the picture I have 4 different kinds of bees (all from Resourceful Bees mod) and all the pedestal is pulling is the regular honeycomb as you can see on the back of the chest.  MC 1.16.3  Pedestals 0.8g  Forge 35.0.14
![image](https://user-images.githubusercontent.com/9939332/99344696-47183780-2856-11eb-9984-52b26f01cd4e.png)

**Comment by Mowmaster** [comment]
ah yes, this is known, and was listed in build version 0.8E changelog on curseforge as 
"Also Added a new upgrade that can harvest honey comb (or bottles if below inventory is supplied empty bottles) from hive blocks (Vanilla Only) Support for modded hives may come later."

Not all bee mods that I've looked at use the same methods as vanilla does for getting comb drops. Unless I make a hacky way to imitate player interaction with the block, and magically absorb the items that are spawned from that interaction.

This isnt a fix, but in all future builds, until this is resolved, i will have an additional tooltip that is displayed for this upgrade specifically: https://github.com/Mowmaster/Pedestals/commit/d6edba19a003b25d7b72feae2057300d2399e41d

**Comment by Rithenar** [comment]
That makes sense. And yeah the only way I have found to automate the interaction with beehives is through *some* user interfaces like Routers as it can use the special tool given by the mod to harvest the hives.

**Comment by Mowmaster** [comment]
Done, will be out in version 0.8m+
https://github.com/Mowmaster/Pedestals/commit/33fe4a71d4793811fc8272366e7879f38584375e
