### ISSUE TITLE
[1.16.4] Exp Grindstone: Not Grinding Enchanted Books

### ISSUE THREAD

**Issue by LoaderB0T** [Mowmaster/Pedestals#23]
Hi, I just started playing around with this awesome mod to automize my enchanting process.

I realized that the Exp Grindstone upgrade does not scrape off the enchantments of enchanted books...
That would be a really nice feature.

Currently, in my modpack, the only way to reset enchanted books back to normal books is by manually using the vanilla grindstone which cannot be automated. Your mod promised to solve that issue but sadly it does not work with books. Any chance you can add that functionality? Or is it configurable somehow?

**Comment by Mowmaster** [comment]
Do you have JEI or Patchouli Installed? Heck, did you even check the Wiki here?
JEI literally has a "description" tab when your viewing the recipe that says this: https://github.com/Mowmaster/Pedestals/blob/1.16/src/main/resources/assets/pedestals/lang/en_us.json#L534
OR WIKI: https://github.com/Mowmaster/Pedestals/wiki/Exp-Grindstone
The very first sentence should be the answer your looking for (Either Link)

If it still doesn't work, post screenshots here of the setup, there is Zero way for me to know what your actually doing if I cant see it :P

**Comment by LoaderB0T** [comment]
Hi @Mowmaster 
First, thanks for the fast reply. Secondly, as a fellow developer, I can understand why you played the "RTFM" card here ^^
Especially since you have great documentation for your mod in comparison to most other even fairly big mods, so props for that!

But I can assure you that I read both the wiki entry and the JEI tooltip. I am also fairly confident my setup is correct as it works for every enchanted weapon, armor, or tool. Just not with books.
My setup here:
![2020-11-23_14 50 43](https://user-images.githubusercontent.com/37637338/99970152-bf718200-2d9b-11eb-918d-a98bfefad6e4.png)
![2020-11-23_14 50 59](https://user-images.githubusercontent.com/37637338/99970160-c13b4580-2d9b-11eb-8f00-5765a0e990ba.png)
It works with a weapon:
![working](https://user-images.githubusercontent.com/37637338/99970423-16775700-2d9c-11eb-8a34-424ae888a41b.gif)
It does not work with a book:
![notWorking](https://user-images.githubusercontent.com/37637338/99970444-22631900-2d9c-11eb-9799-f4977d75511c.gif)

All of that led me to the conclusion that this might be a problem within the mod and not with my setup. Please correct me if I'm wrong here.

**Comment by andrewsf** [comment]
Worth noting than an **Enchanted Book** is not actually a **Book** with enchantments (like a weapon with enchantments). It is a distinct item, so removing all enchantments from it would imply converting it to something else -- maybe a **Book**, **Book and Quill**, maybe air.

However, the JEI description does not make any particular behavior or non-behavior obvious here.

**Comment by LoaderB0T** [comment]
True.

Though even the vanilla grinder can remove enchantments even from books, so I thought this would also make sense for your grindstone,

**Comment by Mowmaster** [comment]
Ah, I apologize, I could have sworn in a past version it used to work, but I just tested in dev and realized you are correct, fortunately its a quick fix and will be included in the next build I publish. If you need this resolved for your personal playthrough I can post a dev build (on request) in my discord if needed.
https://github.com/Mowmaster/Pedestals/commit/7df16b6465226cf175c49d443ef0756dea6193e3

**Comment by LoaderB0T** [comment]
No worries @Mowmaster 
Thanks for the fix, I will wait for the next release :)
