### ISSUE TITLE
Suggestion: Let material generator make less than the maximum amount it can make if there's not enough fluid

### ISSUE THREAD

**Issue by KamiN0Baka** [Mowmaster/Pedestals#230]
I spent like 3 hours trying to get my upgraded material generator to work for obsidian in FTB Skies and was about to post a bug report when I thought to go read through the patch notes. I was in the habit of upgrading them before installing them from setting up all my other generators, so I didn't even think that could be a problem. I realize it's clear in the patch notes for 0.2.49 that it needs to have enough fluid capacity to be able to craft the max amount, but I feel like a lot of people don't think to look there and it would save a some people a lot of time and frustration if this could be changed. 

I do realize that you're working on other issues with the obsidian generation in particular right now and fixing those problems might remedy this, but I feel it needed to be said. Plus maybe anyone who's having the same issue will come here and see this before posting a superfluous bug report.

**Comment by mfrankov** [comment]
I’ll take a look at this when I’m next working on the code - should be relatively straightforward to support in this way.

**Comment by mfrankov** [comment]
fixed in https://github.com/Mowmaster/Pedestals/commit/8d0e8279fff7eda8c66e7ea7859e465fe01bb913 (alongside another bug around "fuel" consumption I noticed while cleaning up the code).

**Comment by Mowmaster** [comment]
released in this version https://github.com/Mowmaster/Pedestals/commit/1c83f5684a4a84458dbea05b8840644e52af1bbc
