### ISSUE TITLE
Farming/harvesting upgrade not working

### ISSUE THREAD

**Issue by Riceball40k** [Mowmaster/Pedestals#232]
I was following a guide to set up an automatic farm using Pedestals after sucessfully using them elsewhere on the same server
However, neither of the upgrades did anything despite checking the configurations carefully and numerous times
I tried multiple small things in an attempt to fix it but nothing worked
The server is running FTB Skies 1.2.1

**Comment by mfrankov** [comment]
The upgrades (`Planter` and `Harvester`) seem to be working without issues for me both in my dev environment and in my FTB Skies 1.2.1.

Do you have the Area Work defined to be on the blocks where the plants will ultimately be (i.e. 1 block above the tilled dirt)? Also are you sure that the work area you selected isn't too large / out of range for your pedestal? Both could be answered by right clicking the pedestal with an upgrade tool to have it render the working area (which if valid will be a green box, and if invalid will be red).

If the work areas are valid, it would also help to know more about what type of crop you're trying to plant and in what setting... but I don't see why this would have stopped working given the harvester has not been changed recently and even though the planter was recently optimized those changes are not yet out in any 1.19 build of pedestals.

**Comment by Riceball40k** [comment]
So I rebuilt the setup again after a while and it seemingly works fine now. Every now and then a crop is missed my the harvester but overall it is running well, even on a larger scale
Not sure what caused the problem but at least it's solved now
Thank you for the reply regardless!

**Comment by mfrankov** [comment]
Ah, another issue could be around whether some of those chunks are claimed and you have them set to disallow fake players (that's something that has even tripped me up in FTBSkies before). Glad it's now resolved however.
