### ISSUE TITLE
Crash for upgrades that use `_numposition` if the work card is replaced after enough iterations with a work card with less positions

### ISSUE THREAD

**Issue by mfrankov** [Mowmaster/Pedestals#235]
Basically, with the base entity refactoring in 1.20 we didn't call `upgrade.actionOnRemovedFromPedestal` for work card removal... and thus in this case we don't reset the `_numposition` nbt and crash due to trying to access an array out of bounds.

Fixed in: https://github.com/Mowmaster/Pedestals/commit/bead77277a0f39c47cc70fd40061039f848c2e9d

**Comment by Mowmaster** [comment]
1.20 fixed: https://github.com/Mowmaster/Pedestals/commit/55918833e4bb5dcbdaa35c038045c66df83659b5
