### ISSUE TITLE
[1.16] - Pedestal Auto Attacker Crashes Server

### ISSUE THREAD

**Issue by SillyFungus** [Mowmaster/Pedestals#25]
On ATM6 when you place a pedestal and put an Auto Attacker upgrade on it and stand next to it so it hits you the server crashes.  Tried this on both a server and single player.  Not sure if its caused by the pack or the Pedestal mod.

**Comment by Mowmaster** [comment]
please check your crashlog to insure that this isnt a duplicate issue to: https://github.com/Mowmaster/Pedestals/issues/24
In the case that it is, there is a 'dev build' on my discord that resolves this until i get an official fix uploaded

**Comment by Mowmaster** [comment]
okay im gonna close this issue, if anyone else encounters this issue, please make sure you are using pedestals version 0.8j or above first, before submitting another similar issue:
https://www.curseforge.com/minecraft/mc-mods/pedestals/files/3126131
