### ISSUE TITLE
[1.16.4] - "Slot 1 not in valid range" Crash

### ISSUE THREAD

**Issue by daviidxestrada** [Mowmaster/Pedestals#26]
[crash-2020-12-03_17.36.00-server.txt](https://github.com/Mowmaster/Pedestals/files/5637800/crash-2020-12-03_17.36.00-server.txt)

Im not really in to a lot of mod development but I hope you can help me get back into my world :) or at least fix the bug.
The modpack im using is atm6, the helper told me that you may be able to give me a hotfix or something like that.

**Comment by Mowmaster** [comment]
please update to pedestals version 0.8j and see if this error still pops up.
https://www.curseforge.com/minecraft/mc-mods/pedestals/files/3126131

**Comment by daviidxestrada** [comment]
oh yes, its fixed, thanks!

**Comment by Mowmaster** [comment]
yeah i actually found this issue when doing the last update so i'm glad i was able to catch it and already have a fix for ya :D
