### ISSUE TITLE
[1.16.4] Crashing autoatacker.

### ISSUE THREAD

**Issue by Namoku** [Mowmaster/Pedestals#27]
When I'm in the are of the pedestal it doesn't give me dmg just freeze and crash the game.
https://pastebin.com/hwdjV8Nq

**Comment by Namoku** [comment]
It's works in last build, sorry. But atm is not yet updated.

**Comment by Mowmaster** [comment]
yeah due to the overwolf transfer from curseforge a lot of packs havent been able to update, but you should be able to do it manually if your in SP, if you cant download it off the site, my discord in the #pedestals chat does have the build as well
