### ISSUE TITLE
[Suggestion] Zinc Crusher Compat

### ISSUE THREAD

**Issue by NillerMedDild** [Mowmaster/Pedestals#31]
Hey o/

It's currently not possible to crush Zinc Ore to Dust with Pedestals, could you add that please? :)

**Comment by Mowmaster** [comment]
do you need me to add ti on my end, or is it something that could be handled with a datapack?

**Comment by NillerMedDild** [comment]
It could easily be added with a datapack, but I was thinking you'd want to support it "natively" - No worries if not :)

**Comment by Mowmaster** [comment]
Once i get configs added to pedestals ill add in more compat then as it can be toggled on and off based on the pack, but for now datapacks might be the best way to add it in if you need it specifically. Ive actually had complaints about the reverse issue where its causing errors when i have recipes without the inputs for them existing in some packs, so its deff something on my TOdO list of things before 1.0 is released.

**Comment by NillerMedDild** [comment]
Heh alright, datapack added, thanks for the extremely fast response!
