### ISSUE TITLE
Magnet Upgrade not Working

### ISSUE THREAD

**Issue by Colton-Slayden** [Mowmaster/Pedestals#32]
I have an item magnet on a pedestal with pedestal area 1 and pedestal Range 2 giving it an effected area of 5x7x5 but it seems to now work it does not pick up items where i believe it should. I have attacked a few pictures to show the are i am working in.
![2020-12-21_01 31 00](https://user-images.githubusercontent.com/32550284/102751031-93aad300-432c-11eb-9032-5d78e5744c8b.png)
![2020-12-21_01 31 10](https://user-images.githubusercontent.com/32550284/102751032-93aad300-432c-11eb-8542-a836e8548cd4.png)
![2020-12-21_01 31 20](https://user-images.githubusercontent.com/32550284/102751033-94436980-432c-11eb-80e0-b5a574021978.png)

**Comment by Mowmaster** [comment]
Please use the Upgrade tool to view the Work Area of the magnet upgrade. This video should help you understand how the tool works: https://youtu.be/l-n4FpS4iJA

From the images provided it appears to be working as intended. Do keep in mind, pedestals work areas are placement dependent.
