### ISSUE TITLE
Teleporter Upgrade - Pedestal Sideways Placement: Requires Eye Level Placement

### ISSUE THREAD

**Issue by desagas** [Mowmaster/Pedestals#33]
# Description
Teleporter Upgrade on Pedestal, with accurate number of range addons, a few sideways pedestal features/bugs:
1. The mod requires that, if the teleporter is placed on the side of a block, it must be at the eye level of the user/player, not at the foot level, as required normally when the teleporter is placed on the top of a block.
2. It requires that you not only enter the block space of the Ped, but also get closer to it than the base of the model allows a user to get. Meaning, you can not touch the top of the pedestal or the bottom of the pedestal to teleport, because you are not close enough to event zone, you actually have to touch the sides, in the few pixel closer to the core than the base allows, again, as 1 mentions, if the Ped is at your head level.
3. You can not teleport by standing on the top of the sideways pedestal (different than above, as top of the pedestal is the literal opposite side of the block it is placed on, where this is the actual top side of the minecraft airspace where the pedestal is placed). However, you can teleport by jumping from under it into the aforementioned pixel space of the block. If the base of the pedestal blocks you, you do not teleport.
4. From what I can see, items entities are not affected by these, they TP just fine from all sides of the pedestal, but not when touching the bottom of it, which I would naturally assume that touching the bottom would not work as it is not in the same block space.
5. 

## Expected Behavior
When entering the block space of the TP, as a player, you teleport to the connected pedestal. Whether it is the users feet or their head, if their hitbox in any way enters that block space, they TP.

# Environment
Forge 1.16.4...13, ATM6 1.3.7, Pedestals 0.81

**Comment by Mowmaster** [comment]
I have verified that sideways placed pedestals at feet level indeed do not tp the player, ill see what i can do to fix this in the future

**Comment by Mowmaster** [comment]
SOOO doing some testing, if you are walking on soul sand when you collide itll teleport just fine, this isnt a fix, but an observation, since the pedestals fan also has this same issue

**Comment by desagas** [comment]
So, it is literally like 2 pixels off or whatever it is. At least you have that to go on.

**Comment by Mowmaster** [comment]
Closing all 1.16 issues, as I am no longer supporting this version of the game and 1.19+ is a full rewrite, I will however accept and merge any fixes folks make for this version.
