### ISSUE TITLE
Very small low priority re-word

### ISSUE THREAD

**Issue by bobothehobo2** [Mowmaster/Pedestals#36]
Just wanted to put this on your radar and it's really non-consequential to the functionality of the mod itself(which from browsing the files for a few mins is coded very cleanly).  There is some wording that could possibly be improved in the mod book json/wiki that is low hanging fruit when you are updating or wanna fold it into an update.  The below feels like the first bullet "Cannot be sent Items, Exp, or Fluids" refers to the pedestal itself and the following two refer to the redstone control.  Might be easier to read and more uniform as "Cannot send items, exp or fluids" or a word re-arrangement of "Items, exp and fluids will not be sent.".  You have a truly unique mod I can see being a staple of packs.  Nice work!

Src Path:
 src/main/resources/data/pedestals/patchouli_books/manual/en_us/entries/gettingstarted/pedestalredstonecontrol.json : Line 11

```
 "pages": [
    {
      "type": "text",
      "text": "$(l:https://github.com/Mowmaster/Pedestals/wiki/Linking-Pedestals%2C-and-Advanced-Uses)A pedestal powered by redstone/$ $(li)Cannot be sent Items, Exp, Energy, or Fluids.$(li)Will prevent its Upgrade from functioning.$(li)Will prevent being teleported to (if connected to a Teleporter upgraded pedestal)"
    },
```

Wiki Path:
https://github.com/Mowmaster/Pedestals/wiki/Linking-Pedestals%2C-and-Advanced-Uses#redstone-control.

Redstone Control
A pedestal powered by redstone:
**### Cannot be sent Items, Exp, Energy, or Fluids.**
Will prevent its Upgrade from functioning.
Will prevent being teleported to (if connected to a Teleporter upgraded pedestal)
Pedestals Emit Redstone when a comparator has been set to read its inventory. (Like any other inventory)
You can create some custom routing situations with pedestals just using the redstone control.

**Comment by Mowmaster** [comment]
https://github.com/Mowmaster/Pedestals/commit/7d5cc0d1aac526f84ce253a16850a804da18f616
also updated wiki page too
