### ISSUE TITLE
exp relay upgrade (blocked)

### ISSUE THREAD

**Issue by CKY-** [Mowmaster/Pedestals#37]
MR master of mow the exp relay blocking upgrade can't accept speed and had now change to capacity  enchants. The regular upgrade  has no issues with these.

**Comment by Mowmaster** [comment]
realized these were not the only ones that wernt setup correctly so i ended up fixing all the filtered related upgrades in the process: https://github.com/Mowmaster/Pedestals/commit/cd7ff1bcdc16643de38bab55a3fee683755541b6
