### ISSUE TITLE
Crash when moved with create mod

### ISSUE THREAD

**Issue by jamzam90** [Mowmaster/Pedestals#39]
Minecraft version 1.16.4
Pedestal version 0.8p
Create version  1.16.3_v0.3

When a pedestal is moved with the create mod it crashes with this log
[crash-2021-01-09_08.38.48-server.txt](https://github.com/Mowmaster/Pedestals/files/5791416/crash-2021-01-09_08.38.48-server.txt)
Issue at creates github
https://github.com/Creators-of-Create/Create/issues/698

**Comment by Mowmaster** [comment]
Closing all 1.16 issues, as I am no longer supporting this version of the game and 1.19+ is a full rewrite, I will however accept and merge any fixes folks make for this version.
