### ISSUE TITLE
Datapack support for Pedestal Crushing

### ISSUE THREAD

**Issue by NillerMedDild** [Mowmaster/Pedestals#4]
Hey o/

It would be really nice if Pedestal Crushing was json/datapack based, that way I would be able to add and remove recipes easily, and unify outputs.

Additionally, would it be possible to only generate Pedestal dust items if the respective ore/ingot is in the instance? I have all sorts of dusts in Enigmatica 6 now that have no ingots, ores or uses.

**Comment by Mowmaster** [comment]
Json recipe support is planned and will come out in the near future as a QOL improvement.
Being able to hide dusts sounds like you need them hidden from JEI? For that I think a config would be needed, which is also on my todo list, since Pedestals currently lacks any configs whatsoever.

**Comment by NillerMedDild** [comment]
Sounds good :)

**Comment by Mowmaster** [comment]
Support added: https://github.com/Mowmaster/Pedestals/commit/d41fb01fc3fca4fd54eff707e33a64fe54bb25e1
Will try to get a build out the 30th so you can add it back to Enigmatica 6 again. 

In the future, please let me know before removing my mod from the pack, I'd be more than willing to make a custom build for you that way players wont have any missing blocks if they update their instances.

ALSO items in the mod that you dont want to appear in JEI as they might be useless for your pack, im not sure this is 100% accurate still, but i do know packmakers should be able to hide items in JEI in some manner: https://www.reddit.com/r/feedthebeast/comments/adb53c/jei_item_hiding/

**Comment by NillerMedDild** [comment]
Thank you!

I'll keep that in mind in the future, I just didn't wanna put any pressure on you to update quickly, and was feeling the pressure myself :P

I don't mind the extra items, as long as I can modify whether they're outputs, so the datapack update fixes my concern for item hiding, but thank you :)
