### ISSUE TITLE
Massive FPS lag when using Fan Pedestal

### ISSUE THREAD

**Issue by gmartens** [Mowmaster/Pedestals#42]
Running Pedestals 0.8p in Enigmatica 6 Modpack on a private server.
I built a mob farm and wanted to use the fan pedestals. I enchanted them with varying levels of range, speed and area. As soon as I put the Fan Upgrade in the Pedestal, my FPS drops by about 20. Having 3 pedestals with fans drops the FPS to slide show levels. As soon as I remove the upgrades, my FPS returns to a more reasonable level. The TPS on the server was still fine with them all going, so there is something strange going on with the rendering. Friends on the server also confirmed that it was causing lag for them. 
Thanks for the awesome mod, I am excited to try out its other features. There is some truly innovative stuff here!

**Comment by Mowmaster** [comment]
im not entirely sure what could be causing this, 
I do know i made a massive amount of optimization changes from p --> r so if possible i would recommend updating the pedestals version when possible.
My testing, version P first
![version P](https://user-images.githubusercontent.com/10681506/105108643-51d29100-5a80-11eb-8b16-aef33c7ed44e.png)
and R second
![version R](https://user-images.githubusercontent.com/10681506/105108669-6020ad00-5a80-11eb-99df-858fd4374d83.png)

There is a fps increase after updating, so this is my recommendation, if possible.
I was speaking to an e6 dev tonight so it does appear they are looking to do a pack update in the near future, but if its you and a few others, manually updating shouldn't be too much trouble
