### ISSUE TITLE
Repairing with anvil no longer works

### ISSUE THREAD

**Issue by hvdklauw** [Mowmaster/Pedestals#43]
For E6 modpack (normally 0.8p I think) I upgraded to 0.8r and repairing with the exp anvil no longer worked.

Downgraded and loaded the game and it instantly repaired again.

Didn't change anything else expect upgrade/downgrade the mod.

**Comment by Mowmaster** [comment]
i borked it on accident for the default upgrade, but enchanting it with capacity would have fixed it.
its fixed in latest hotfix: https://github.com/Mowmaster/Pedestals/commit/094e5050e12c20d8a996fc4e752ff0ba8fc9fe94
