### ISSUE TITLE
Invalid/Malformed Recipes?

### ISSUE THREAD

**Issue by HalestormXV** [Mowmaster/Pedestals#46]
I noticed on server load-up you might have some malformed/invalid recipes? Or is this something unrelated? I actually just noticed this appears to be on 0.8q which is what CurseForge auto-installed. I haven't tred the -.8r_hotfix_4 that forge just now populated for me. Here is the recipes for historic purposes if they have indeed not yet been fixed.

https://pastebin.com/sE27uvwj

**Comment by Mowmaster** [comment]
yeah those should be fixed in the latest version.
