### ISSUE TITLE
Items being voided

### ISSUE THREAD

**Issue by CKY-** [Mowmaster/Pedestals#47]
Here is a short clip of what  is happening after  ATM6 1.5.0 update with pedestals 0.8r_hotfix_4..
https://clips.twitch.tv/CulturedFrozenReubenDoritosChip

**Comment by Mowmaster** [comment]
ah okay, yeah all filtered magnet type functions will have this issue (regular magnet is fine) ill fix it when i get a chance.

**Comment by Pecant-Pie** [comment]
The glitch also can cause a dupe if you have itemstacks larger than one in the filter inventory

**Comment by Mowmaster** [comment]
i suspected this was the case, im completely redoing how filtering works, so all filtered upgrades will be starting to be phased out in the next release

**Comment by Mowmaster** [comment]
removed filtered magnet upgrades, they will be replaced by using a normal magnet with a filter on it in the next version.
Since itll use the same check system as when i check if an item can be sent to a filtered pedestal, it shouldnt cause a dupe like this every again.
