### ISSUE TITLE
Dupe

### ISSUE THREAD

**Issue by ja132** [Mowmaster/Pedestals#49]
I used a magnet with the mod filter upgrade and it would change the picked up item into the item that was in the filter chest below the pedestal and then send that new “duped” item to the selected chest. 

Ex:
diamond in filter chest 
dirt dropped and picked up by pedestal turns to diamond 
+diamond in the receiving chest

**Comment by Mowmaster** [comment]
removed filtered magnet upgrades, they will be replaced by using a normal magnet with a filter on it in the next version.
Since itll use the same check system as when i check if an item can be sent to a filtered pedestal, it shouldnt cause a dupe like this every again.
