### ISSUE TITLE
!HELP¡ silk touch echantment in cobble generator 

### ISSUE THREAD

**Issue by SRJ0KER007** [Mowmaster/Pedestals#50]
when i try to enchant the cobble generator in exp anvil and the items move aroun the pedestals and nothing happend, someone can give me a tip or and explanation about the echantment because the wiki only say use the exp anvil and nothing more , and I think it's a nonsense and vain explanation. regards

**Comment by BlueAgent** [comment]
The exp anvil uses the item in the chest under the main pedestal and combines it with the items in the surrounding pedestals (on the 4 cardinal directions 1 block away from the main pedestal).

You'll want to first put the items on the surrounding pedestals then put the item you want to enchant in the chest under the main pedestal and then it should enchant if it has enough experience inside and put the item onto the main pedestal.

There's an in-game book for the Pedestals mod you can read for this information.

**Comment by Mowmaster** [comment]
https://www.youtube.com/watch?v=n0xMD9qBm5E
