### ISSUE TITLE
Player shows as [Pedestals] on Tab list

### ISSUE THREAD

**Issue by kosma** [Mowmaster/Pedestals#51]
We've had several cases where a player (in all cases a Pedestals mod user) has been shown as [Pedestals] on the player list. This morning I logged in and saw it happen to myself and thought I should report. This is probably related to changes done in #19.

Sadly I don't have reproduction instructions as this is a rather intermittent issue. The following pedestals are present in my base (the area where I logged in): import, craft 1x1, block placer, block breaker, export, liquid xp import, xp dropper. In this particular case the bug occurred immediately upon login; I don't know about other cases.

Environment: Enigmatica E6 0.3.13, multiplayer.

![image](https://user-images.githubusercontent.com/1089580/108224221-f48f3580-713a-11eb-89c7-576db5ec137b.png)

**Comment by kosma** [comment]
Update:
- The issue persists even if I log out and back in,
- The issue resolves itself upon server restart.

Based on the above, maybe this is how it happens?
- Server is restarted (we do overnight restart)
- Someone loads chunks containing someone else's pedestals
- The pedestals perform some automated activity
- The name [Pedestals] is assigned to the player, and stays that way

**Comment by Nalebaen** [comment]
Also, it seems to be removing some recipes in JEI.  I get the bug quite often and I think it's related to changing dimension.  I'll do more testing.

**Comment by Mowmaster** [comment]
> Also, it seems to be removing some recipes in JEI. I get the bug quite often and I think it's related to changing dimension. I'll do more testing.

JEI recipes changing, unless theyre tied specifically to your player, would be an unrelated issue, check jei issues before attempting to blame me for that :P

**Comment by Nalebaen** [comment]
Sorry for trying to help by providing additional information. I won't do it again!

**Comment by Mowmaster** [comment]
IDK if this is fixed or not, but i did a thing. let me know if it still happens in 0.8s +

**Comment by Hurricaneforces** [comment]
It still changed my name to [Pedestals] in Atm6 sky pack (ver 1.0.7)

Pedestals ver 0.8s+

**Comment by Mowmaster** [comment]
hrmm, alright, will try something else next time then

**Comment by Mowmaster** [comment]
(next) version 0.8t should have another fix for this, Ill reopen the issue if it persists after the update: https://github.com/Mowmaster/Pedestals/commit/0e13a72f736e7d354df053da745115a6ca764d40

**Comment by Mowmaster** [comment]
This is fixed in the 0.8s hotfix 4 version. 'Sorta'
You will have to go around removing the upgrades (upgrade tool in offhand + left click) and re inserting them for this change to take place.

This isnt a 'true' fix, but more like an aesthetic one.
The pedestal will now remember your current in game display name, and when the server starts up, instead of the pedestal using "[Pedestals]" and attaching it to your UUID, itll now use your Display Name, as it was when you inserted the upgrade.
