### ISSUE TITLE
Pedestal sounds are projected from all pedestals

### ISSUE THREAD

**Issue by Jomeaga** [Mowmaster/Pedestals#57]
Playing ATM6 In The Sky 1.0.2. I've built a bunch of block placers/block breaker pairs with hammers to get resources. The sound from them was annoying so I put down Cyclic soundproofing, problem solved. But then when I'm near some of my other pedestals like my crusher, the sounds from the other pedestals are projected from them.

Are sounds not produced individually?

**Comment by Jomeaga** [comment]
The specific sound that was playing was "item.armor.equip_generic:minecraft"

**Comment by SocialSpy** [comment]
Same thing was happening for me as well. It would be nice to have a mute upgrade of some sort.

**Comment by Mowmaster** [comment]
I dont want to hear any complaints if i add a mute option, and then people cant tell if their upgrades are working or not! :P

Yeah ill probably just add an augment item for this. does the recipe take wool, or a sheep entity to craft though...

**Comment by Mowmaster** [comment]
alright sound muffler is implemented, and will be in the next update, if global sounds are still a thing after update 0.8s, please repost this issue

**Comment by devmattrick** [comment]
I'm still having issues with sounds not being played in the correct location. For me, its no longer emanating from pedestals but I can hear it at a specific location in my world (I'm assuming world spawn?).
