### ISSUE TITLE
**E6 0.4.7* Combining Upgrade with Filter Removes Enchantments

### ISSUE THREAD

**Issue by TemperedFool** [Mowmaster/Pedestals#59]
I'm not clear if this is intended behavior - user of E6 reports crafting an enchanted magnet upgrade with a filter removes the enchantments.

Pedestals version pedestals-0.8r_hotfix_4

**E6 0.4.7*

**Describe the bug**
Combining an enchanted magnet upgrade with a filter upgrade crafts an unenchanted upgrade.

**Screenshots**

![Image 1](https://cdn.discordapp.com/attachments/308008312291721216/825399736894095360/unknown.png)
![Image 2](https://cdn.discordapp.com/attachments/308008312291721216/825399796344160287/unknown.png)

__Originally posted by @SkyChotik in https://github.com/NillerMedDild/Enigmatica6/issues/1833__

**Comment by Mowmaster** [comment]
Using an item in a recipe generally voids its enchants, this isnt a new thing, SOME mods do have a way to keep enchants, but thats a custom thing they do, there is no default behavior for this in the base game.

PLUS all filtered upgrades are being deprecated in the next update(and removed in the one after that), so this wont be an issue going forward.
The new system will be the normal magnet, with a filter item inserted into the pedestal with the filter swapper tool. Filters will be set by crouch + right clicking the filter item on an inventory.
