### ISSUE TITLE
Auto Attacker doesn't target Magma Slimes with Iron or Diamond Block.

### ISSUE THREAD

**Issue by Keb911** [Mowmaster/Pedestals#6]
Auto Attacker doesn't target magma slimes with an iron or diamond block under it. 

MC: 1.16.1
Forge Version: 32.0.108
Pedestals: 0.7c

**Comment by Mowmaster** [comment]
Give the Coal Block a try, it will target all MobEntities. https://github.com/Mowmaster/Pedestals/wiki/Filtering-By-Entity (Towards the bottom)
