### ISSUE TITLE
Block Breaker - Bug

### ISSUE THREAD

**Issue by RobertLSnead** [Mowmaster/Pedestals#62]
ver. 0.8s

The block breaker in the previous release, collected what block was broken and would store in the pedestal for collection and would stop when the pedestal was full.  The current release 0.8s now breaks the block and just drops the item into the world, you then need a magnet to collect.  When using a placer in conjunction it is impossible to stop the flow of items all over the place.  Eventually the magnet and storage unit gets full and items have no where to go or there is no way to stop the breaker.  Was this intended with the new release for the breaker to not collect the item?

**Comment by RobertLSnead** [comment]
I guess enchanting with the magnet helped with the pickup, however it still does not stop breaking when the pedestal can hold no more.

**Comment by Mowmaster** [comment]
it never stopped breaking once it was full... i might be able to add that in a future update though?

**Comment by Mowmaster** [comment]
I said 'f it' and did this: https://github.com/Mowmaster/Pedestals/commit/82b5eff7cd7dfa7655690a06d06d5f9bc13aa7d1
But yeah, default magnet funtionality was moved to an enchant, too many folks didnt like it on by default, so its an option now.

hotfix update will be out shortly...
