### ISSUE TITLE
Pedestals Wont Accept Mods ATM 6 Skyblock

### ISSUE THREAD

**Issue by MinecraftPhoenix** [Mowmaster/Pedestals#65]
Been trying to put a cobble mod onto a pedestal and it just adds it likes its an item I have no idea why its doing that

**Comment by MinecraftPhoenix** [comment]
![2021-04-04_20 48 28](https://user-images.githubusercontent.com/81929283/113519951-a10c6600-9587-11eb-935a-a87b49f5acef.png)

**Comment by Mowmaster** [comment]
https://github.com/Mowmaster/Pedestals/issues/64
