### ISSUE TITLE
!!! - Upgrades not being applied with right click. They are insert instead.

### ISSUE THREAD

**Issue by Mowmaster** [Mowmaster/Pedestals#67]
The 0.8s+ update changed pedestal interaction. Since noone actually reads changelogs I'll link this video here:
https://youtu.be/N3Doz6OKjmY

If, after using the new changes for a while, you have suggestions to improve the interactions, comment them here.

**Comment by Sv443** [comment]
Would be great if this would be added to the in game guide book. I just spent like 30 minutes trying to figure it out until I found the 5 seconds in the above video that mentioned this change. I'm not salty, I just want to spare others this time.

**Comment by Mowmaster** [comment]
the next main update to the mod will have a fully reworked documentation, and ill try to keep it updated going forwards now that new content is slowing down to reworks and more complex single upgrades

**Comment by Sv443** [comment]
> the next main update to the mod will have a fully reworked documentation, and ill try to keep it updated going forwards now that new content is slowing down to reworks and more complex single upgrades
  
Sounds good, thanks for the extremely fast reply :)

**Comment by Mowmaster** [comment]
Closing this 'issue' cause it's been out almost a month now
