### ISSUE TITLE
Can't apply the modifier on to the pedestal

### ISSUE THREAD

**Issue by Tekmix11** [Mowmaster/Pedestals#68]
For some reason I can't get the modifier attacked to the pedestal when im right clicking...
Im playing all the mods 6 into the sky
I crafted the cobble gen modifier and tried to right click the pedestal with it, but the only thing thats happening is that the pedastal is holding the item on top.

**Comment by Mowmaster** [comment]
Look at other issues before you post 
https://youtu.be/N3Doz6OKjmY
