### ISSUE TITLE
Attack upgrade causes massive TPS lag

### ISSUE THREAD

**Issue by sssssss340** [Mowmaster/Pedestals#69]
Version: Pedestals - 1.16.5_0.8s_hotfix_1

The pedestal attack upgrade causes massive TPS lag, even when unupgraded and unfiltered. I believe this is related to the creation of a new fake player for every single attack. That player should be reused, saving on game resources.

**Comment by Mowmaster** [comment]
hopefully this fixes it, if not, then ill have to move fake player init to the TE later.
