### ISSUE TITLE
Anyway to port to 15.2 ?

### ISSUE THREAD

**Issue by mostwantedpwnz** [Mowmaster/Pedestals#7]
Hey there, I haven't yet gone to 16 yet, wondering if you can port for 15.2!  appreciate the work you've put in, hope to use your mod!

**Comment by Mowmaster** [comment]
I have considered a 1.15.2 port AFTER i get version 1.0 out for 1.16+
For a time frame, at least a month before i get v1.0 out, so itll be some time after that.

**Comment by mostwantedpwnz** [comment]
> I have considered a 1.15.2 port AFTER i get version 1.0 out for 1.16+
> For a time frame, at least a month before i get v1.0 out, so itll be some time after that.

Gotta love the work you put in brother, says its going to take a month, two hours later its done!
