### ISSUE TITLE
[Request] Project MMO Compatibility

### ISSUE THREAD

**Issue by faeldray** [Mowmaster/Pedestals#70]
Project MMO is a mod where you can level up different skills (agility, combat, farming, cooking, smithing, etc.) and you get better and better perks as you level.

So specifically, it would be great if the smelting upgrades gave smithing/cooking XP depending on what it's processing. Also, the perks of smithing and cooking are that you get an increased chance of extra outputs as you level. So it would be great if the smelting upgrades also supported that.

https://www.curseforge.com/minecraft/mc-mods/project-mmo

**Comment by Mowmaster** [comment]
A quick look at the CF post and i dont notice an API right away. Also I probably wont do any compat with other mods outside of recipe type stuff till this mod is finished (1.17+ probably) As i also plan to make an API for this mod to support people making addons, that way if i dont get around to it, someone could still make their own addon for it eventually

**Comment by faeldray** [comment]
There is an API available and listed about 3/4 down on [this page](https://harmonised7.github.io/minecraft/pmmo/Features.html), although I don't know how helpful that is. But it's understandable if you don't want to add any compats.

![image](https://user-images.githubusercontent.com/967709/113919102-cfb55700-97a8-11eb-889c-82b691cebf4c.png)

I could _attempt_ to make a compatibility mod but I'm not really experienced with Java. Judging from the [PMMO Bridge mod](https://github.com/MintTeaTx/PMMOBridge/tree/main/src/main/java/com/minttea/pmmobridge/events) that already provides compat for Ars Noveau and Blood Magic, I think I would just need an event to hook into. But I guess that would be the API you're talking about?

**Comment by Mowmaster** [comment]
I should probably make an API for pedestals at some point, then i could make an addon for this specifically, or someone else could, even those mods that do it for other mods already could also add pedestals once i have an api. Since ive never made an api before and dont know where to start on it, i'd say it could be a long while before this happens. My current plans are api and mod finished in 1.17 version of minecraft, but that just depends on my motivation and how my reworks of some old features goes.

**Comment by Mowmaster** [comment]
Closing all 1.16 issues, as I am no longer supporting this version of the game and 1.19+ is a full rewrite, I will however accept and merge any fixes folks make for this version.
