### ISSUE TITLE
Smart Import Upgrade not working with new Filters

### ISSUE THREAD

**Issue by KevinZinn** [Mowmaster/Pedestals#71]
I've swapped out my deprecated filtered export (item) upgrade with a regular export upgrade and the new filter (item), but my smart importer won't send items to the pedestal.

things I've tried:
 - unlinking and relinking the pedestals
 - crafting a new smart import upgrade and using it
 - breaking and replacing the pedestal

Mod version:
- v0.8-hotfix-1

Modpack info:
- All The Mods 6: To The Sky v1.0.6

**Comment by Mowmaster** [comment]
This is the setup being used on my test server: 
![image](https://user-images.githubusercontent.com/10681506/113984883-31111080-9811-11eb-9356-c68b259a1cb5.png)
It does work fine, Ive had 0 issues with it thus far.

If youve broken all related pedestals, relinked them, and tried a differnt upgrade, the only thing(s) i can think of is:
1. Use the Filter tool, right click on a filtered pedestal, it should tell you what the filter inserted is, and whats being filtered for.
2. My gut feeling says you probably inserted a blank, whitelist filter. Which means you need to watch this: https://youtu.be/azaeIA8UjiQ

Export Filters in this version do not 'auto detect' what they need to filter by, the process I used before was checking the inventory 'below' every time an item would try to be passed to it, which in larger setups can be really laggy. (Other filters used a pre setup inventory below it checked, this required physical items to be used to set the filter, and could be very costly in setups with multiple 'layers' of filters needing a very expensive item)

The current system uses pre-set filters and checks those, which does make this less dynamic in a sense, but also means that you don't have to be careful not to pull all the items out of an inventory causing it to no longer filter that item.
If you still need a slightly dynamic filtering option, the tag and mod filters are pretty awesome to use.

Hopefully that helps.

**Comment by KevinZinn** [comment]
That was my problem, thanks
