### ISSUE TITLE
Trouble linking when Upgrades are already installed

### ISSUE THREAD

**Issue by MuteTiefling** [Mowmaster/Pedestals#73]
Version: pedestals-0.8s_hotfix_1

It just doesn't seem to work. I put down an XP Anvil Pedestal, an EXP Tank Pedestal, and a Fluid to XP Pedestal, then tried to link them. Just get the following in chat when sneak right click the second pedestal to complete the link. 

![image](https://user-images.githubusercontent.com/9543430/114288920-76b42000-9a41-11eb-950b-977c9c696af9.png)

**Comment by MuteTiefling** [comment]
Apparently this is also only in creative mode

**Comment by Mowmaster** [comment]
I've never had this happen in creative mode, it just looks like your not crouching since that's the right click interaction. Is the link tool in your off hand by chance? Pretty sure you need to use it only in your main hand.

**Comment by MuteTiefling** [comment]
I've realized it was due to me flying, actually. I'm holding sneak and using the tool in my main hand. But I'm also holding space to not drop down. Seems to all cancel out the sneak.
