### ISSUE TITLE
Dupe Issue

### ISSUE THREAD

**Issue by Knightmarevive** [Mowmaster/Pedestals#75]
putting pedestal near to Mekanism pipe when Pedestals player is not allowed in FTB chunks and destroying it results in dupe of pedestals.
![pedestal](https://user-images.githubusercontent.com/40168735/114977275-b3d84200-9e87-11eb-9b4e-a6556ccf111f.png)

**Comment by Knightmarevive** [comment]
It may be or might not conflict with minecolonies...
(there is my colony upwards)

**Comment by devbence** [comment]
Hi, more context to the issue:
Just checked, I'm able to break the pedestals, except they dont break, they just drop a pedestal, but I was able to break it with a Cyclic Block Breaker, it worked as intended.
I tested chunkloaded, not chunkloaded areas also.

(modpack: atm6, v1.6.0, pedestals ver: 0.8s_hotfix_2)

**Comment by Mowmaster** [comment]
turns out this was caused by me trying to make a nice way for creative players no not break the pedestal trying to pull items out, should fix it with this: https://github.com/Mowmaster/Pedestals/commit/3dba23c1360442721c62bc9ba99d2207669b4f77
