### ISSUE TITLE
Enchanting issues

### ISSUE THREAD

**Issue by Catandcomparator** [Mowmaster/Pedestals#76]
I was playing around with atm 6, but for some reason i was unable to enchant an an advanced book at an enchantment table. it just says "limited enchantability"

**Comment by Mowmaster** [comment]
you specifically need an enchanter that can enchant at over level 90 AND can enchant treasure type enchants. Currently the only enchanter with both capabilities to do this is the pedestals enchanter. Which is the intended way to do this.

**Comment by Catandcomparator** [comment]
I tried both an apotheosis one, and a pedestals one. Neither seem to work.

**Comment by Mowmaster** [comment]
only the pedestals one will work, apoth cannot do treasure type enchants. Watch this and see if it helps: https://youtu.be/re0MKJEI_P4?t=1452
