### ISSUE TITLE
Block breaker/Block Placer upgrades not working?

### ISSUE THREAD

**Issue by Shindur** [Mowmaster/Pedestals#8]
Version: 1.16.1 0.8
Enigmatica 6 modpack

Steps to reproduce:
Place down pedestal
Place block breaker upgrade on pedestal
Nothing happens?

Even tried linking it to a pedestal with the import upgrade, but all that does is take the pickaxe I put on it off. Maybe I'm being a potato.. but I think it's broken.

**Comment by Shindur** [comment]
Same kinda issue with block placer as well

Steps to reproduce:
Place down pedestal
Place block placer upgrade on pedestal
Place blocks that need placing on pedestal
Nothing happens?

**Comment by Mowmaster** [comment]
If the area is claimed with FTB chunks (or whatever) you have to add 'Minecraft' as an allie in the add allies section
![2020-08-29_20 12 12](https://user-images.githubusercontent.com/10681506/91648974-f69df480-ea33-11ea-8fa1-524aa65cb078.png)

Please try this first, and get back to me if your still having issues.

**Comment by Shindur** [comment]
It was a claimed chunk issue.. didn't think to look there. Thank you!
