### ISSUE TITLE
[1.16.5] Crash with Fluid Exporter

### ISSUE THREAD

**Issue by NillerMedDild** [Mowmaster/Pedestals#80]
Relayed from: https://github.com/NillerMedDild/Enigmatica6/issues/2068

- `pedestals-0.8r_hotfix_4`

Forgive me if this was fixed already, I didn't find the issue in my search :)

> **Describe the bug**
> Using pedestals to transfer an empty bucket from one pedestal to another one with the fluid export upgrade causes the game and server to crash. Loading into the world causes the same crash again.
> 
> **Logs**
> https://ghostbin.co/paste/gjmxr
> Ghostbin since pastebin is under maintenance right now
>

**Comment by Mowmaster** [comment]
fixed (like a month ago nearly), update to latest

**Comment by NillerMedDild** [comment]
I have, the player hasn't 😄 thanks!
