### ISSUE TITLE
[Request] - Enchant downgrading

### ISSUE THREAD

**Issue by Hiranus** [Mowmaster/Pedestals#81]
As far as I can tell no mod provides such functionality, and it could be very helpful to be able to lower level of enchant on enchanted book. For example I have bought from villager  Pedestal Area 5 book but I need Pedestal Area 1. There is no way to get that currently.

**Comment by Mowmaster** [comment]
Have you maybe tried enchanting the area focus book at a low level in the enchanting table? Because depending on what level you enchant at you can get basically any level you want.
