### ISSUE TITLE
Pedestal Range VI not increased.

### ISSUE THREAD

**Issue by Slyklaw** [Mowmaster/Pedestals#82]
Range VI gives 15.
Area VI gives 13, same as Area V.

![2021-04-30_13 31 59](https://user-images.githubusercontent.com/44900062/116663098-d8243a80-a9c0-11eb-8f7d-e0fa2105e8a6.png)

**Comment by Mowmaster** [comment]
yeah you need the advanced enchant to exceed level 5, hence the test in red saying "...to unlock its full potential, apply the advanced enchant to it."
