### ISSUE TITLE
Possible enchantment dupe

### ISSUE THREAD

**Issue by NillerMedDild** [Mowmaster/Pedestals#83]
Relayed from: https://github.com/NillerMedDild/Enigmatica6/issues/697

It's likely that this issue no longer exists in newer Pedestals versions, but I haven't found the time to try and reproduce it. 

> It is possible to enchant multiple pedestal upgrades with one book and taking all of those upgrades, and using enchantment extractor, stripping each upgrade to their books, meaning using one book to make many.

**Comment by Mowmaster** [comment]
Im going to assume this is an old bug, OR some mod is modifying the anvil behavior and ignoring the methods that would normally restrict this from happening.
As far as I can tell, From pedestals by itself, this isnt possible.
![image](https://user-images.githubusercontent.com/10681506/116884645-9677d780-abec-11eb-8e44-692affe2385e.png)
