### ISSUE TITLE
Smelting gunpowder does nothing

### ISSUE THREAD

**Issue by The--Captain** [Mowmaster/Pedestals#84]
Pedestals with smelting upgrades do not smelt gunpowder into redstone as JEI suggests.  Smelting other things (cobblestone, etc) works as expected.

**Comment by Mowmaster** [comment]
there are 2 types of recipes for the crushers/furnaces/sawmills
this is similar to the 2 recipe lists for the cobble gen.

did you verify that the recipe you looked at was for the normal upgrade, or the upgrade with the advanced enchant on it?

**Comment by Mowmaster** [comment]
closing this since im betting it was a misunderstanding of the jei normal and advanced furnace functions
