### ISSUE TITLE
Cobble Generator Upgrade stops functioning after a short while

### ISSUE THREAD

**Issue by surfersmurf** [Mowmaster/Pedestals#85]
I'm on ATM6 Skyblock with Pedestals 0.8 hotfix_3 installed.

I have the setup like in the photo, but after a short amount of time the pedestal stops working. The first time it generated 48 netherrack, then I had to break everything and replace it. Only reinserting the upgrade didn't help, I had to break the pedestal itself. The second time it produced 33 netherrack.

Note, that on the picture the netherrack on top of the pedestal is missing. It used to be there while it was working.

![2021-05-13_17 47 30](https://user-images.githubusercontent.com/26865417/118152135-aa091680-b414-11eb-8028-e0509741411a.png)

**Comment by Mowmaster** [comment]
After some testing hoppers below pedestals can cause issues, as to why this is, i really dont know. 

As for your setup, i'd take your hopper and make an export upgrade out of it, then use pedestal transferring as that doesnt cause any issues.
Alt: I'm wondering why you need the chest for the storage? The cobble gen will store up to 2 billion in it, and most other pipe mods can pull out of it just fine.

**Comment by Mowmaster** [comment]
https://github.com/Mowmaster/Pedestals/commit/0efbf9541f3b6dd8a1c92aa99392d2e4837da6b0
