### ISSUE TITLE
2x2 compressor with blacklisted items deletes blacklisted items while trying to compress

### ISSUE THREAD

**Issue by PenguinSquire** [Mowmaster/Pedestals#86]
I have a system set up to take the drops from compressed gravel through a heavy oak sieve and smelt/compress them into the ore block form (ex: iron block, inferium block, etc.)

After picking up the drops with magnet upgrades and putting them into a barrel, I compress ore pieces into ore chunks, smelt them, and send them back to the original chest.

There is a 3x3 compressor and a 2x2 compressor attached to this chest, but the 2x2 has a blacklist of iron trapdoors and iron ingots. The 2x2 compressor appears to try to compress the iron into iron trapdoors, but as it is blacklisted, the iron does not appear on the pedestal, but also disappears from the chest.

When I contacted you about it, you said that the most likely scenario was that with the filter,  "[the insert fails, but the code doesn't have an error catch and removes the items from the inv assuming it worked](https://discord.com/channels/314719788351881218/725528892051554304/844039867326660639)"

**Comment by Mowmaster** [comment]
https://github.com/Mowmaster/Pedestals/commit/61bfa4f218d9ab0b05b234d818a908761ea52fd9

**Comment by Mowmaster** [comment]
apparently using the pedestals override doesnt actually force items into the pedestal, somewhere the filter is still being checked...

**Comment by Mowmaster** [comment]
https://github.com/Mowmaster/Pedestals/commit/78a2639214b29f9470e74b9e96a8ba91348409da

**Comment by Mowmaster** [comment]
https://github.com/Mowmaster/Pedestals/commit/510ab6e11506fa3c45278fbbab742e8f76767aa9

**Comment by Mowmaster** [comment]
so while i didnt do a true fix for this, the fix is, you cant insert a filter onto a crafter upgraded pedestal, nor can you put this on a pedestal with a filter already on it
