### ISSUE TITLE
Filtering Import upgrades (normal and smart) can void items

### ISSUE THREAD

**Issue by skzskormz** [Mowmaster/Pedestals#88]
Smart Import Upgrade is voiding items while enchanted with Capacity V or Speed V. The effect is worse if you have both enchantments and Pedestal Speed Augments
Setup to reproduce:
Chest with Smart Restock Upgrade receiving items from a Chest with Smart Import Upgrade with Capacity V or/and Speed V

**Comment by SimenHus** [comment]
I have the same problem when using a filter on a pedestal that has a normal import Speed IX Capacity IX enchantment.

**Comment by sbenedict** [comment]
Similar issue here with Import Upgrade. Import upgrade pulling from chest with a whitelist item filter pulls items not on the whitelist and then they are 'voided'.

Version: 0.8s_hotfix_3

**Comment by Mowmaster** [comment]
https://github.com/Mowmaster/Pedestals/commit/66d0e04b2274ebb128ea7c9f26826ecf7f4d75da
