### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by benbenlaw** [Mowmaster/Pedestals#89]
Can you change you recipe outputs to tag items from this 
{
  "type": "pedestals:pedestal_crushing",
  "ingredient": {
    "tag": "forge:ores/nickel"
  },
  "result": {
    "item": "pedestals:dustnickel",
    "count": 2
  }
}

To this
{
  "type": "pedestals:pedestal_crushing",
  "ingredient": {
    "tag": "forge:ores/nickel"
  },
  "result": {
    "tag": "forge/dustsnickel",
    "count": 2
  }
}

**Comment by benbenlaw** [comment]
have made a pull request that changes most of the ore outputs to tags

**Comment by Mowmaster** [comment]
Is there any reason why this can't just be handled with a tweeker mod or datapack specified by the modpack? Ore unification is probably ideally handled as tagged input and specific item output, otherwise you can end up with wierd results where one mods steel isn't compatible for another mods multiblock.

Mekanism does this tagged output thing, and I know it caused huge headaches for both atm6 and e6 modpacks early on until they made their own ore unifier mods and tweeked the recipes, I only ever added ore dusts for atm6 at the start, so I was actually considering removing those items and the related recipes completely, leaving it up to pack devs to tweek things as they see fit.

If anything, I can release a separate file of kubeJS tweeks for ore inputs to item outputs if needed.

**Comment by benbenlaw** [comment]
yeah so i do have a custom script that replaces the output to mekanism stuff first however it doesnt always work for example clicking on your dusts shows no recipes but the dust is still made in the pedestal. maybe a kubejs script could work

**Comment by Mowmaster** [comment]
i made this script for the direwolf20 pack + pedestals, so if you havent already, this would probably work for a kubeJS script.

`
events.listen('recipes', event => {
   const crusher_tag = (input, output, count) => {
        event.custom({
            "type": 'pedestals:pedestal_crushing',
            "ingredient": {
                "tag": input
            },
            "result": {
                "item": output,
                "count": count
            }
        })
    }
	
	
	const crusher_item = (input, output, count) => {
        event.custom({
            "type": 'pedestals:pedestal_crushing',
            "ingredient": {
                "item": input
            },
            "result": {
                "item": output,
                "count": count
            }
        })
    }
	
	const crusher_item_advanced = (input, output, count) => {
        event.custom({
            "type": 'pedestals:pedestal_crushing_advanced',
            "ingredient": {
                "item": input
            },
            "result": {
                "item": output,
                "count": count
            }
        })
    }
	
	const cobblegen = (input, output, count) => {
        event.custom({
            "type": 'pedestals:pedestal_cobblegen',
            "ingredient": {
                "item": input
            },
            "result": {
                "item": output,
                "count": count
            }
        })
    }
	
	const cobblegen_silk = (input, output, count) => {
        event.custom({
            "type": 'pedestals:pedestal_cobblegensilk',
            "ingredient": {
                "item": input
            },
            "result": {
                "item": output,
                "count": count
            }
        })
    }
	
	const fluidtoxp = (input, output, count) => {
        event.custom({
            "type": 'pedestals:pedestal_fluid_to_xp',
            "ingredient": {
                "item": input
            },
            "result": {
                "item": output,
                "count": count
            }
        })
    }
	

	crusher_tag('forge:sand', 'create:limesand', 1)
	crusher_tag('forge:terracotta', 'minecraft:red_sand', 1)
    crusher_tag('forge:ores/uranium', 'mekanism:dust_uranium', 2)
    crusher_tag('forge:ores/osmium', 'mekanism:dust_osmium', 2)
    crusher_tag('forge:ores/nickel', 'thermal:nickel_dust', 2)
    crusher_tag('forge:ores/cinnabar', 'thermal:cinnabar', 2)
    crusher_tag('forge:ores/silver', 'thermal:silver_dust', 2)
    crusher_tag('forge:ores/tin', 'thermal:tin_dust', 2)
    crusher_tag('forge:ores/copper', 'thermal:copper_dust', 2)
    crusher_tag('forge:ores/lead', 'thermal:lead_dust', 2)
	crusher_tag('forge:netherrack', 'cinder_flour', 2)
	
	crusher_tag('forge:charcoal', 'mekanism:dust_charcoal', 1)
	crusher_tag('forge:ingots/netherite', 'mekanism:dust_netherite', 1)
	crusher_tag('forge:obsidian', 'mekanism:dust_obsidian', 4)
	crusher_tag('forge:coal_coke', 'immersiveengineering:dust_coke', 1)
	crusher_tag('forge:storage_blocks/coal_coke', 'immersiveengineering:dust_coke', 9)
	crusher_tag('forge:ingots/hop_graphite', 'immersiveengineering:dust_hop_graphite', 1)
	crusher_tag('forge:ingots/cyanite', 'bigreactors:cyanite_dust', 1)
	crusher_tag('forge:ingots/graphite', 'bigreactors:graphite_dust', 1)
	crusher_tag('forge:wool', 'minecraft:string', 4)
	crusher_tag('forge:terracotta', 'minecraft:red_sand', 1)
	crusher_tag('forge:gems/fluix', 'appliedenergistics2:fluix_dust', 1)
	crusher_tag('forge:gems/certus_quartz', 'appliedenergistics2:certus_quartz_dust', 1)
	crusher_tag('forge:gems/quartz', 'appliedenergistics2:nether_quartz_dust', 1)
	crusher_tag('forge:ender_pearls', 'appliedenergistics2:ender_dust', 1)
	
	
	crusher_item('mana-and-artifice:vinteum_ore', 'mana-and-artifice:vinteum_dust', 2)
	crusher_item('minecraft:coal', 'mekanism:dust_coal', 1)
	crusher_item('minecraft:stick', 'thermal:sawdust', 1)
	crusher_item('minecraft:nether_wart_block', 'minecraft:nether_wart', 9)
	crusher_item('minecraft:fern', 'minecraft:green_dye', 1)
	crusher_item('minecraft:large_fern', 'minecraft:green_dye', 2)
	crusher_item('minecraft:grass', 'minecraft:wheat_seeds', 1)
	crusher_item('minecraft:tall_grass', 'minecraft:wheat_seeds', 2)
	crusher_item('minecraft:soul_soil', 'minecraft:soul_sand', 1)
	
	crusher_item_advanced('minecraft:flint', 'minecraft:gunpowder', 1)
	
	cobblegen('mysticalagriculture:soulium_block', 'minecraft:soul_soil', 1)
	cobblegen('minecraft:granite', 'create:granite_cobblestone', 1)
	cobblegen('minecraft:diorite', 'create:diorite_cobblestone', 1)
	cobblegen('minecraft:andesite', 'create:andesite_cobblestone', 1)
	cobblegen('create:dolomite', 'create:dolomite_cobblestone', 1)
	cobblegen('create:gabbro', 'create:gabbro_cobblestone', 1)
	cobblegen('create:scoria', 'create:scoria_cobblestone', 1)
	cobblegen('create:dark_scoria', 'create:dark_scoria_cobblestone', 1)
	cobblegen('create:limestone', 'create:limestone_cobblestone', 1)
	cobblegen('create:limestone', 'create:limestone_cobblestone', 1)
	cobblegen('mysticalagriculture:soulstone', 'mysticalagriculture:soulstone_cobble', 1)
	
	cobblegen_silk('appliedenergistics2:smooth_sky_stone_block', 'appliedenergistics2:sky_stone_block', 1)
	
	fluidtoxp('cyclic:xpjuice_bucket', 'minecraft:experience_bottle', 49)
	fluidtoxp('bloodmagic:life_essence_bucket', 'minecraft:experience_bottle', 7)
	fluidtoxp('astralsorcery:liquid_starlight_bucket', 'minecraft:experience_bottle', 20)
`
