### ISSUE TITLE
Game crash while using auto-attacker on raid captain vindicator

### ISSUE THREAD

**Issue by douyabian** [Mowmaster/Pedestals#9]
Modpack: Enigmatica 6
Pedestals version: pedestals-1.16.1_0.8

Was messing around with auto-attacker upgrade with vindicator spawn eggs and game started crashing after a while
Realised that it crashes when a vindicator with a raid captain banner spawns and gets killed by the pedestal and managed to reproduce it.

Steps to reproduce: 
Set up auto-attacker pedestal
Spawn vindicators with eggs until raid captain shows up
Capture/Move raid captain over to pedestal area to get killed
Crash

maybe something to do with bad omen

Heres the crash log if it will help:

https://pastebin.pl/view/raw/2f7eccdd

**Comment by Mowmaster** [comment]
fixed in commit: https://github.com/Mowmaster/Pedestals/commit/4ed63db9a60f426bfd6c28483f89bee7c737a53b
Ill try to get it pushed in the build on the 5th or 6th.
