### ISSUE TITLE
Bad Interaction between Compact Machines and Bonemeal fed Fertilizer upgrade

### ISSUE THREAD

**Issue by metachaos** [Mowmaster/Pedestals#90]
Modpack: All the Mods 6 skyblock
Interaction with: Compact Machines and Mystical Agriculture
Pedestal upgrade: Fertilizer, with speed and area enchantments

I created a mystical agriculture garden in a compact machine, then added a pedestal with a fertilizer upgrade. I then automatically fed bonemeal into that pedestal.

When feeding bonemeal into the pedestal, instead of increasing the actual rate of growth of the plants in the compact machine, it creates plants in the same chunk, in the overworld. You can watch as they are continually grown and replaced. They will replace any blocks put into that chunk at that y level. This creates massive lag as the entities fall into the void.

Once bonemeal is no longer fed into the pedestal, the creation of extra entities ceases.

**Comment by Mowmaster** [comment]
this should fix it, will be out in version 0.8t https://github.com/Mowmaster/Pedestals/commit/184f5e28f7e8dae46bb38d15e08877f60978c503
