### ISSUE TITLE
java.lang.NullPointerException: Ticking block entity [Crash]

### ISSUE THREAD

**Issue by Ki-Tan2934** [Mowmaster/Pedestals#93]
**-Version** pedestals-0.8s_hotfix_3.jar
**-Forge** forge-1.16.5-36.1.24.jar
https://paste.ubuntu.com/p/dt7vBTXNZy/
This was a server crash and I do not know how to make this crash reoccur, hope you can gain something out of this

**Comment by Mowmaster** [comment]
fixed already now that i look at it: https://github.com/Mowmaster/Pedestals/commit/184f5e28f7e8dae46bb38d15e08877f60978c503
