### ISSUE TITLE
Pedestals Randomly Crashing with Block Breaker Upgrade

### ISSUE THREAD

**Issue by RobuxShooters** [Mowmaster/Pedestals#97]
Version: 0.8s hotfix 3

I'm not quite sure if this issue has been reported before, but I seem to be randomly crashing while performing normal tasks such as chopping trees. The crash logs say that it was caused by the block breaker upgrade. The modpack is Enigmatica 6 v0.5.0 and I do have OptiFine installed along with OptiForge, but I don't think they can cause non-graphical-related issues.

The crash logs are as follows:
[crash-2021-06-25_18.13.49-server.txt](https://github.com/Mowmaster/Pedestals/files/6717123/crash-2021-06-25_18.13.49-server.txt)
[crash-2021-06-25_23.02.13-server.txt](https://github.com/Mowmaster/Pedestals/files/6717125/crash-2021-06-25_23.02.13-server.txt)

**Comment by Mowmaster** [comment]
Have you tried it without optifine/optiforge?
I only ask as I've been running this pack on a server for weeks without issues, and this specific issue seems to be caused by something that should occur on a large majority of the upgrades as well.

Can you give me any additional info about this block breaker, like what its breaking, or where its at (dim/biome/height/etc)?

I think i have an idea why it is happening, but i need more info to know for sure.

**Comment by RobuxShooters** [comment]
Sorry, but I have not tried it without OptiFine/OptiForge, since it does make it relatively difficult to play with the pack (FPS issues and such). I could try it without those mods though, but it may take a while.

As for any additional info,
Dimension: Overworld
Biome: Savanna Scrub
Position in world: x=956, y=60, z=5041

- There are no blocks present under the block breaker (it is not breaking anything) at the time of the crash.
- The block breaker is active and not powered by a redstone signal at the time of the crash.
- The only enchantment on the block breaker is Pedestal Speed V. I have stripped off both Pedestal Range V and Pedestal Magnet from the upgrade before putting it on the pedestal.
- There is a block placer pedestal that tries to place blocks in the space where the block breaker would break the block.
- The block placer upgrade is active and not powered by a redstone signal at the time of the crash.
- The block placer upgrade is not placing anything at the time of the crash.
- The only enchantment on the block placer upgrade is Pedestal Speed V.
- I have other pedestals (cobble gen, energy importer, energy exporter, energy relay) which are also always active and not powered by a redstone signal at the time of the crash.

The pedestal block placer + block breaker setup:
![image](https://user-images.githubusercontent.com/16001607/123457961-103da780-d617-11eb-9c3c-423d63faec29.png)

**Comment by Mowmaster** [comment]
alright, only issue I can think of, i was using an old, and probably bad way of getting the server world, so ill consider this 'fixed' for now until after the next update, and it it continues to occur we can reopen the issue.
https://github.com/Mowmaster/Pedestals/commit/13e3093fabd7cde75715f7dddd901c93aa2bde8e
