### ISSUE TITLE
Crash on Item Attack upgrade usage

### ISSUE THREAD

**Issue by TheTechPny** [Mowmaster/Pedestals#98]
https://pastebin.com/dwgY4EAX
^ Crash Report ^

Server crashes as soon as an Attack Upgrade is used on a pedestal

**Comment by Mowmaster** [comment]
please update your version to latest to see if the problem persists: https://www.curseforge.com/minecraft/mc-mods/pedestals/files/3279192

**Comment by Mowmaster** [comment]
havent gotten a reply on this, so closing the issue

**Comment by TheTechPny** [comment]
The problem is solved now, thanks!
